### ISSUE TITLE
Where is the Autoload.php ?

### ISSUE THREAD

**Issue by vv-varun** [mvar/apache2-log-parser#4]
When I use the example, I get the error that autoload.php not found ... 
Am I missing something ?

I am referring to the following code:
`require __DIR__ . '/vendor/autoload.php';`

It is looking for vendor folder in the current directory which it can't find. 
Moreover, there is no autoload.php anywhere in the project files.. 

I am new to using composer .. so this autoload.php is confusing me...

**Comment by mvar** [comment]
Hi @mastram 

You need to install dependencies using Composer in order to have vendors directory and `autoload.php`.

Please follow these simple steps:

1. Create `composer.json` with following content:

```json
{
    "require": {
        "mvar/apache2-log-parser": "^2.1"
    }
}
```

2. Download Composer from here: https://getcomposer.org/download/

3. Run command to install dependencies:

```
composer install
```
